version: '3.8'

services:
  jekyll:
    image: jekyll/jekyll:4.2.2
    container_name: shouten-v2-jekyll
    command: jekyll serve --host 0.0.0.0 --livereload --force_polling
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll
      - jekyll_bundle:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development

volumes:
  jekyll_bundle:
